# Generated by Django 3.2.3 on 2021-09-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='attributes',
            field=models.ManyToManyField(help_text='A listing attribute is something that this listing may have, such as a size, as specified by its class', through='listings.ListingAttributeValue', to='listings.ListingAttribute', verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, help_text='Show this listing in search results and listings.', verbose_name='Is public'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='product_class',
            field=models.ForeignKey(blank=True, help_text='Choose what type of listing this is', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.listingclass', verbose_name='Listing type'),
        ),
    ]
